import {game,input,ui} from '../src/main.js';
import {CONFIG as C,SKILL_IDS,ULTIMATE_IDS,center} from '../src/config.js';
import {pilot} from './pilot.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),paint=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))),assert=(ok,m)=>{if(!ok)throw Error(m);};
const log=m=>{const li=parent.document.createElement('li');li.textContent=m;parent.document.querySelector('#results').append(li);};
const key=(type,code)=>window.dispatchEvent(new KeyboardEvent(type,{code,bubbles:true,cancelable:true})),tap=code=>{key('keydown',code);key('keyup',code);};
const ready=id=>{game.reset();game.showInstructions();game.startRun();game.selectUltimate(id);game.enterStage();game.spawnQueue=[];game.spawnWarnings=[];game.enemies=[];game.phase='test';ui();};
async function checks(){
  game.reset();ui();tap('Enter');await paint();tap('Enter');await paint();assert(game.state==='ultimateSelect'&&document.querySelectorAll('[data-choice]').length===5,'5択');tap('Digit5');await paint();assert(game.ultimateChoice==='cannon','数字5');tap('Enter');for(let i=0;i<120;i++)game.update(.01,{});assert(game.state==='playing'&&game.activeEnemies.length+game.spawnWarnings.length>0,'即時出現');log('PASS Enter進行、必殺技5択、約1秒の敵出現');
  for(const id of ULTIMATE_IDS){ready(id);game.ultimate=100;tap('KeyK');await paint();assert(game.ultimate===0,`${id}発動`);}log('PASS 5必殺技の発動');
  const left=document.querySelector('[data-input="left"]'),attack=document.querySelector('[data-input="attack"]');for(const b of [left,attack])b.setPointerCapture=()=>{};const ptr=(b,type,id)=>b.dispatchEvent(new PointerEvent(type,{pointerId:id,bubbles:true,clientX:b.getBoundingClientRect().x+4,clientY:b.getBoundingClientRect().y+4}));ready('exit');game.hero={...game.hero,x:200,y:300,facing:{x:-1,y:0},attackCd:0};game.createEnemy('slime',{x:150,y:300});const x=game.hero.x;ptr(left,'pointerdown',1);ptr(attack,'pointerdown',2);await sleep(70);assert(game.hero.x<x&&game.enemies[0].hp<40,'同時入力');ptr(left,'pointerup',1);ptr(attack,'pointerup',2);assert(!input.debug().held.size,'解除');log('PASS スマホ相当の移動＋攻撃同時入力');
  ready('exit');game.loadStage(6,true);game.state='bossIntro';const b=game.spawnBoss();assert(b.rankIndex===5&&C.rankBosses[5].phases===3,'社長');b.hp=b.maxHp*.3;b.phaseSeen=new Set(C.rankBosses[5].patterns[0]);game.updateRankBoss(b,.01);assert(b.bossPhase===3,'3形態');log('PASS 6役職設定、社長3形態');log('ALL BROWSER CHECKS PASSED');
}
async function play(){const priority={reply:130,thunder:125,meteor:120,drone:115,boomerang:95,slash:80,shredder:60,gauge:45,heal:40};game.reset();game.showInstructions();game.startRun();game.selectUltimate('exit');let guard=0;while(game.state!=='result'&&guard++<C.timeLimit*60){if(game.state==='upgrade'){let best=0,score=-1;game.offers.forEach((id,i)=>{const s=(priority[id]||0)+(game.skills[id]||0)*8;if(s>score){score=s;best=i;}});game.chooseUpgrade(best);}else if(game.state==='stageIntro')game.enterStage();else if(game.state==='bossIntro')game.spawnBoss();else if(game.state==='playing')game.update(1/60,pilot(game));if(guard%360===0){ui();await paint();}}ui();assert(game.outcome==='success'&&game.clearedWaves===12,'通し');log(`PASS 6ステージ・6ボス・退勤 / ${game.elapsed.toFixed(1)}秒 / ${game.kills}体`);}
async function visual(){location.href='/?showcase=late';}
try{const mode=new URL(import.meta.url).searchParams.get('mode');mode==='play'?await play():mode==='visual'?await visual():await checks();}catch(e){log('FAIL '+e.message);console.error(e);}
