import {game,input,ui,beginStory,nextStory,skipStory} from '../src/main.js';import {CONFIG as C,ULTIMATE_IDS} from '../src/config.js';import {pilot} from './pilot.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),paint=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))),assert=(ok,m)=>{if(!ok)throw Error(m);},log=m=>{const li=parent.document.createElement('li');li.textContent=m;parent.document.querySelector('#results').append(li);};
const key=(type,code)=>window.dispatchEvent(new KeyboardEvent(type,{code,bubbles:true,cancelable:true})),tap=code=>{key('keydown',code);key('keyup',code);};
const ready=id=>{game.reset();game.showInstructions();game.startRun();game.selectUltimate(id);game.enterStage();game.spawnQueue=[];game.spawnWarnings=[];game.enemies=[];game.phase='wave';ui();};
const ptr=(el,type,id,x,y)=>el.dispatchEvent(new PointerEvent(type,{pointerId:id,pointerType:'touch',button:0,bubbles:true,cancelable:true,clientX:x,clientY:y}));
async function checks(){
  game.reset();ui();beginStory('opening');await paint();assert(!document.querySelector('#story-overlay').hidden,'opening visible');assert(document.querySelector('#story-image').src.includes('story-opening-v2.webp'),'opening art');assert(document.querySelector('#story-art').classList.contains('q1'),'opening crop 1');nextStory();assert(document.querySelector('#story-count').textContent==='2 / 4','opening advance');assert(document.querySelector('#story-art').classList.contains('q2'),'opening crop 2');skipStory();assert(game.state==='instructions','opening skip');beginStory('opening');skipStory();log('PASS 専用オープニング画像・4場面進行・スキップ・再表示');
  game.reset();game.showInstructions();game.startRun();ui();assert(game.state==='ultimateSelect'&&document.querySelectorAll('[data-choice]').length===5,'5択');tap('Digit5');await paint();assert(game.ultimateChoice==='cannon','数字5');tap('Enter');for(let i=0;i<120;i++)game.update(.01,{});assert(game.state==='playing'&&game.activeEnemies.length+game.spawnWarnings.length>0,'即時出現');log('PASS 必殺技5択と約1秒の敵出現');
  for(const id of ULTIMATE_IDS){ready(id);game.ultimate=100;tap('KeyK');await paint();assert(game.ultimate===0,`${id}発動`);}log('PASS 5必殺技の発動');
  const canvas=document.querySelector('#game'),ult=document.querySelector('[data-input="ultimate"]');canvas.setPointerCapture=()=>{};ult.setPointerCapture=()=>{};ready('exit');game.hero={...game.hero,x:200,y:300,facing:{x:1,y:0},attackCd:0};game.createEnemy('slime',{x:255,y:300});const r=canvas.getBoundingClientRect(),points=[[r.left+r.width*.2,r.top+r.height*.25],[r.left+r.width*.68,r.top+r.height*.64]];for(let i=0;i<points.length;i++){const [x,y]=points[i];ptr(canvas,'pointerdown',10+i,x,y);assert(input.read().x===0&&input.read().y===0,'deadzone');ptr(canvas,'pointermove',10+i,x+55,y+22);assert(input.read().x>.8,'360 move');ptr(canvas,'pointerup',10+i,x+55,y+22);assert(input.read().x===0&&document.querySelector('#joystick-base').hidden,'release');}
  const [x,y]=points[0];ptr(canvas,'pointerdown',20,x,y);ptr(canvas,'pointermove',20,x+60,y);game.ultimate=100;ptr(ult,'pointerdown',21,r.right-25,r.bottom-25);const simultaneous=input.read();assert(simultaneous.x>.9&&simultaneous.ultimate,'move plus ultimate');game.update(.4,simultaneous);ptr(ult,'pointerup',21,r.right-25,r.bottom-25);assert(input.read().x>.9,'ultimate release keeps move');ptr(canvas,'pointermove',20,x+400,y+300);assert(Math.hypot(input.read().x,input.read().y)<=1.01,'clamped');ptr(canvas,'pointercancel',20,x+400,y+300);assert(input.debug().joystick.pointerId===null,'cancel');log('PASS ステージ内の複数位置、360度、必殺同時入力、pointerId独立');
  const gear=document.querySelector('#settings');ptr(gear,'pointerdown',30,r.right-20,r.top+20);gear.click();assert(input.debug().joystick.pointerId===null&&!document.querySelector('#settings-panel').hidden,'settings does not start move');document.querySelector('#settings-close').click();log('PASS 必殺技・設定UIではスティックを開始しない');
  ready('exit');const count=game.hero.attackCount;game.createEnemy('slime',{x:game.hero.x+50,y:game.hero.y});game.update(.4,{});assert(game.hero.attackCount>count,'auto attack');const before=game.remaining;window.dispatchEvent(new Event('blur'));game.update(.05,{});assert(game.state==='playing'&&game.remaining<before,'focus loss does not pause');log('PASS 自動攻撃と停止なし');
  ready('exit');game.finish('success');ui();await paint();assert(!document.querySelector('#story-overlay').hidden&&game.state==='ending','ending opens');assert(document.querySelector('#story-image').src.includes('story-ending-v2.webp'),'ending art');for(let i=0;i<3;i++)nextStory();assert(document.querySelector('#story-art').classList.contains('q4'),'ending crop 4');skipStory();assert(game.state==='result','ending skip to result');log('PASS 専用エンディング画像・4場面と結果画面');log('ALL BROWSER CHECKS PASSED');
}
async function play(){const priority={reply:130,thunder:125,meteor:120,drone:115,boomerang:95,slash:80,shredder:60,gauge:45,heal:40};game.reset();game.showInstructions();game.startRun();game.selectUltimate('exit');let guard=0;while(game.state!=='result'&&guard++<C.timeLimit*60){if(game.state==='upgrade'){let best=0,score=-1;game.offers.forEach((id,i)=>{const s=(priority[id]||0)+(game.skills[id]||0)*8;if(s>score){score=s;best=i;}});game.chooseUpgrade(best);}else if(game.state==='stageIntro')game.enterStage();else if(game.state==='bossIntro')game.spawnBoss();else if(game.state==='ending')game.completeEnding();else if(game.state==='playing')game.update(1/60,pilot(game));if(guard%360===0){ui();await paint();}}ui();assert(game.outcome==='success'&&game.clearedWaves===12,'通し');log(`PASS 6ステージ・6ボス・退勤・エンディング / ${game.elapsed.toFixed(1)}秒 / 最低気力${game.telemetry.minEnergy.toFixed(0)} / 回復${game.telemetry.healed.toFixed(0)}`);}
async function visual(){location.href='/?showcase=late';}try{const mode=new URL(import.meta.url).searchParams.get('mode');mode==='play'?await play():mode==='visual'?await visual():await checks();}catch(e){log('FAIL '+e.message);console.error(e);}
