import test from 'node:test';
import assert from 'node:assert/strict';
import {CoopGame,COOP_RULES,safeInput} from '../src/coop/game.js';
import {validSnapshot,createInvite,readInvite,CoopLink,interpolateSnapshots} from '../src/coop/network.js';
import {blocked} from '../src/pathfinding.js';
const empty=()=>{const g=new CoopGame(['exit','blackhole'],()=>.5);g.queue=[];g.phase='boss';return g;};
test('two independent inputs are bounded, normalize diagonal speed and expire when packets stop',()=>{const g=empty();const before=g.players.map(p=>({x:p.x,y:p.y}));g.setInput(0,{x:Infinity,y:NaN,ultimate:1});assert.deepEqual(g.players[0].input,{x:0,y:0,ultimate:false});g.setInput(0,{x:100,y:0});g.setInput(1,{x:1,y:1});g.update(.1);assert.ok(Math.abs(g.players[0].x-before[0].x-17)<.01);assert.ok(Math.abs(Math.hypot(g.players[1].x-before[1].x,g.players[1].y-before[1].y)-17)<.01);for(let i=0;i<10;i++)g.update(.1);const x=g.players[0].x;g.update(.1);assert.equal(g.players[0].x,x);assert.deepEqual(safeInput(null),{x:0,y:0,ultimate:false});});
test('each player takes damage separately; revive needs three continuous seconds and fails through desks',()=>{const g=empty(),[a,b]=g.players;a.invulnerable=0;g.hurt(a,100);assert.equal(a.down,true);assert.equal(b.hp,100);a.x=200;a.y=300;b.x=235;b.y=300;g.revive(2);assert.equal(a.down,true);b.x=400;g.revive(.1);assert.equal(a.revive,0);b.x=235;g.revive(3);assert.equal(a.down,false);assert.equal(a.hp,40);a.invulnerable=0;g.hurt(a,100);a.x=110;a.y=190;b.x=110;b.y=245;g.revive(4);assert.equal(a.down,true);b.invulnerable=0;g.hurt(b,100);g.update(.1);assert.equal(g.state,'failure');});
test('players choose separate upgrades, duplicate or unknown choices cannot advance twice',()=>{const g=empty();g.state='upgrade';g.wave=1;assert.equal(g.choose(0,'reply'),true);assert.equal(g.choose(0,'slash'),false);assert.equal(g.choose(1,'bad'),false);assert.equal(g.state,'upgrade');assert.equal(g.choose(1,'orbit'),true);assert.equal(g.state,'playing');assert.equal(g.wave,2);assert.equal(g.players[0].skills.reply,1);assert.equal(g.players[1].skills.orbit,1);assert.equal(g.players[1].skills.reply,0);});
test('every ultimate consumes only its owners gauge and cannot recharge during its effect',()=>{for(const id of ['exit','clones','rush','blackhole','cannon']){const g=empty();const p=g.players[0];p.ultimate=id;p.gauge=100;const e=g.spawn('slime',{x:200,y:480});e.state='move';assert.equal(g.useUltimate(p),true);assert.equal(p.gauge,0);assert.equal(g.players[1].gauge,35);g.hit(e,1000,p);assert.equal(p.gauge,0);assert.equal(g.useUltimate(p),false);assert.ok(p.lock>p.effect);}});
test('snapshot is JSON transferable, detached, bounded, and rejects malformed data',()=>{const g=empty();g.spawnBoss();g.update(.1);const s=JSON.parse(JSON.stringify(g.snapshot()));assert.equal(validSnapshot(s),true);s.players[0].hp=12;assert.equal(g.players[0].hp,100);s.players[0].x=Infinity;assert.equal(validSnapshot(s),false);assert.equal(validSnapshot(null),false);const bad=g.snapshot();bad.enemies[0].dir=null;assert.equal(validSnapshot(bad),false);});
test('wave and boss spawns respect full body collisions and enemy cap',()=>{const g=empty();for(let i=0;i<60;i++)g.spawn(i%2?'brute':'slime');assert.equal(g.enemies.length,COOP_RULES.maxEnemies);assert.ok(g.enemies.every(e=>!blocked(e.x,e.y,e.radius,g.solids)));});
test('boss defeat opens gate but both players must reach it alive',()=>{const g=empty();g.spawnBoss();g.boss.state='move';g.hit(g.boss,2000,g.players[0]);assert.equal(g.phase,'escape');g.players[0].x=420;g.players[0].y=60;g.update(.1);assert.equal(g.state,'playing');g.players[1].x=415;g.players[1].y=65;g.update(.1);assert.equal(g.state,'success');});
test('invite retains repository path and uses fragment, invalid invites rejected',()=>{const key='a'.repeat(32),room='teiji-'+ 'b'.repeat(32);const url=new URL(createInvite('https://example.test/game/index.html?debug=1',room,key));assert.equal(url.pathname,'/game/coop.html');assert.equal(url.search,'');assert.deepEqual(readInvite(url.hash),{room,key});assert.equal(readInvite(''),null);assert.throws(()=>readInvite('#room=bad'));});
class Emitter{events={};on(name,fn){(this.events[name]??=[]).push(fn);}emit(name,...args){for(const fn of this.events[name]||[])fn(...args);}}
class Conn extends Emitter{open=true;sent=[];dataChannel={bufferedAmount:0};send(m){this.sent.push(m);}close(){this.open=false;this.emit('close');}}
test('host accepts ordered input only, not forged snapshots; timeout closes connection once',()=>{let now=0,closed=0;const received=[];const link=new CoopLink(null,{now:()=>now,onMessage:m=>received.push(m),onClosed:()=>closed++});link.role='host';link.started=true;link.attach(new Conn());link.conn.emit('open');link.receive({v:1,type:'snapshot',data:{}});link.receive({v:1,type:'input',seq:3,input:{x:400,y:0}});link.receive({v:1,type:'input',seq:2,input:{x:-1}});assert.equal(received.length,1);assert.equal(received[0].input.x,1);now=7000;link.poll();assert.equal(closed,1);assert.equal(link.closed,true);link.poll();assert.equal(closed,1);});
test('backpressure terminates instead of queuing unbounded snapshots',()=>{let closed=false;const link=new CoopLink(null,{onClosed:()=>closed=true});link.attach(new Conn());link.conn.emit('open');link.conn.dataChannel.bufferedAmount=130000;assert.equal(link.sendSnapshot({}),false);assert.equal(closed,true);});
test('interpolation affects display only and preserves enemy removals',()=>{const a=empty().snapshot(),b=structuredClone(a);b.players[0].x+=20;const m=interpolateSnapshots(a,b,.5);assert.equal(m.players[0].x,a.players[0].x+10);assert.equal(b.players[0].x,a.players[0].x+20);});
class FakePeer extends Emitter{
 static registry=new Map();static waiting=[];
 constructor(id){super();this.id=id||'guest-'+FakePeer.registry.size;FakePeer.registry.set(this.id,this);FakePeer.waiting.push(()=>this.emit('open',this.id));}
 connect(id,options){const host=FakePeer.registry.get(id),local=new Conn(),remote=new Conn();remote.metadata=options.metadata;local.open=remote.open=false;local.send=m=>{if(!local.open)throw new Error('closed');FakePeer.waiting.push(()=>remote.emit('data',structuredClone(m)));};remote.send=m=>{if(!remote.open)throw new Error('closed');FakePeer.waiting.push(()=>local.emit('data',structuredClone(m)));};local.close=remote.close=()=>{if(!local.open&&!remote.open)return;local.open=remote.open=false;FakePeer.waiting.push(()=>{local.emit('close');remote.emit('close');});};FakePeer.waiting.push(()=>{host.emit('connection',remote);local.open=remote.open=true;remote.emit('open');local.emit('open');});return local;}
 destroy(){FakePeer.registry.delete(this.id);}
 static flush(){for(let i=0;FakePeer.waiting.length&&i<100;i++)FakePeer.waiting.shift()();assert.equal(FakePeer.waiting.length,0);}
}
test('two simulated peers complete invite, ready, controls, upgrades and synchronized result; reject third guest',()=>{
 FakePeer.registry.clear();let hostGame=null,guestView=null,ready=null;const host=new CoopLink(FakePeer,{onMessage:m=>{if(m.type==='ready')ready=m.ultimate;if(m.type==='input')hostGame.setInput(1,m.input);if(m.type==='choice')hostGame.choose(1,m.skill);}});host.open();FakePeer.flush();const guest=new CoopLink(FakePeer,{onMessage:m=>{if(m.type==='snapshot')guestView=m.data;}});guest.open({room:host.room,key:host.key});FakePeer.flush();assert.equal(host.connected,true);assert.equal(guest.connected,true);guest.send('ready',{ultimate:'cannon'});FakePeer.flush();assert.equal(ready,'cannon');hostGame=new CoopGame(['exit',ready]);host.started=true;host.send('start',{ultimates:['exit',ready]});FakePeer.flush();assert.equal(guest.started,true);
 guest.sendInput({x:1,y:0});FakePeer.flush();hostGame.update(.1);host.sendSnapshot(hostGame.snapshot());FakePeer.flush();assert.equal(guestView.players[1].x,hostGame.players[1].x);assert.ok(guestView.players[1].x>270);
 hostGame.state='upgrade';hostGame.choose(0,'reply');guest.send('choice',{skill:'orbit'});FakePeer.flush();assert.equal(hostGame.wave,2);assert.equal(hostGame.players[1].skills.orbit,1);
 let rejected=false;const third=new CoopLink(FakePeer,{onClosed:()=>rejected=true});third.open({room:host.room,key:host.key});FakePeer.flush();assert.equal(rejected,true);assert.equal(host.connected,true);
 hostGame.end('success','test result');host.sendSnapshot(hostGame.snapshot());FakePeer.flush();assert.equal(guestView.state,'success');host.close();FakePeer.flush();assert.equal(guest.closed,true);
});
test('wrong invitation key cannot occupy the host guest slot',()=>{FakePeer.registry.clear();const host=new CoopLink(FakePeer);host.open();FakePeer.flush();let rejected=false;const intruder=new CoopLink(FakePeer,{onClosed:()=>rejected=true});intruder.open({room:host.room,key:'0'.repeat(32)});FakePeer.flush();assert.equal(rejected,true);assert.equal(host.conn,null);host.close();});
test('rendering serialized combat and rescue snapshots never uses invalid geometry',async()=>{const {renderCoop}=await import('../src/coop/render.js');const ctx=new Proxy({},{get:(obj,key)=>obj[key]??((...args)=>{for(const arg of args)if(typeof arg==='number')assert.ok(Number.isFinite(arg),String(key));}),set:(obj,key,value)=>{obj[key]=value;return true;}});const g=empty();g.spawnBoss();g.boss.state='warn';g.boss.attack='charge';g.players[0].down=true;g.players[0].hp=0;g.players[1].effect=2;g.players[1].ultimate='clones';g.effect('beam',g.players[1],380,.2,1);renderCoop(ctx,JSON.parse(JSON.stringify(g.snapshot())),1,1);});
test('waiting host reconnects after signaling suspension, keeping the invite and guest slot',()=>{FakePeer.registry.clear();let now=100;const statuses=[];const host=new CoopLink(FakePeer,{now:()=>now,onStatus:s=>statuses.push(s)});host.open();FakePeer.flush();const room=host.room,key=host.key;let reconnects=0;host.peer.disconnected=true;host.peer.reconnect=()=>{reconnects++;host.peer.disconnected=false;host.peer.emit('open');};host.peer.emit('disconnected');assert.equal(host.closed,false);host.resume();host.poll();assert.equal(reconnects,1);assert.equal(host.room,room);assert.equal(host.key,key);assert.equal(host.conn,null);assert.deepEqual(statuses,['waiting','reconnecting','waiting']);host.close();});
test('reconnect attempts are bounded and expose a useful failure reason',()=>{FakePeer.registry.clear();let now=100,message='';const host=new CoopLink(FakePeer,{now:()=>now,onClosed:m=>message=m});host.open();FakePeer.flush();host.peer.reconnect=()=>{};host.peer.emit('disconnected');for(let i=0;i<4;i++){now+=5001;host.poll();}assert.equal(host.closed,true);assert.match(message,/signaling-reconnect/);});
