import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game.js';
import {pilot} from './pilot.js';
import {blocked} from '../src/pathfinding.js';
import {CONFIG as C} from '../src/config.js';
function choose(g,priority){let best=0,score=-Infinity;g.offers.forEach((id,i)=>{const s=(priority[id]??10)+(g.skills[id]||0)*8;if(s>score){score=s;best=i;}});return best;}
function run(seed,ultimate,priority){const random=()=>((seed=seed*16807%2147483647)-1)/2147483646,g=new Game(random);g.showInstructions();g.startRun();g.selectUltimate(ultimate);const seen={waves:new Set(),stages:new Set(),bosses:new Set(),types:new Set(),maxEnemies:0,maxBullets:0,gate:false};for(let ticks=0;ticks<C.timeLimit*60&&g.state!=='result';ticks++){if(g.state==='upgrade'){seen.types.add(g.upgradeType);g.chooseUpgrade(choose(g,priority));continue;}if(g.state==='stageIntro'){g.enterStage();continue;}if(g.state==='bossIntro'){const b=g.spawnBoss();seen.bosses.add(b.rankIndex+1);continue;}if(g.state!=='playing')continue;if(g.phase==='wave')seen.waves.add(`${g.stage}-${g.wave}`);seen.stages.add(g.stage);seen.gate||=g.phase==='escape';seen.maxEnemies=Math.max(seen.maxEnemies,g.activeEnemies.length);seen.maxBullets=Math.max(seen.maxBullets,g.enemyProjectiles.length);g.update(1/60,pilot(g));assert.equal(blocked(g.hero.x,g.hero.y,C.radius,g.solids),false);}return {g,seen,report:{ultimate:g.selectedUltimate?.name,outcome:g.outcome,elapsed:Number(g.elapsed.toFixed(2)),kills:g.kills,hits:g.hitsTaken,maxEnemies:seen.maxEnemies,maxBullets:seen.maxBullets,skills:g.skillSummary()}};}
test('ranged build clears six stages, six bosses, and final gate',()=>{const {g,seen,report}=run(7,'exit',{reply:130,thunder:125,meteor:120,drone:115,boomerang:95,slash:80,shredder:60,gauge:45,heal:40});console.log(JSON.stringify({build:'ranged',...report}));assert.equal(g.outcome,'success');assert.equal(seen.waves.size,12);assert.deepEqual([...seen.stages],[1,2,3,4,5,6]);assert.equal(seen.bosses.size,6);assert.ok(seen.gate);assert.ok(seen.maxEnemies>=30);assert.ok(g.kills>=350);assert.ok(g.elapsed<C.timeLimit);});
test('close build with rush also clears the full route',()=>{const {g,seen,report}=run(19,'rush',{slash:140,shredder:135,boomerang:120,drone:90,reply:85,thunder:80,meteor:70,gauge:55,heal:45});console.log(JSON.stringify({build:'close',...report}));assert.equal(g.outcome,'success');assert.equal(seen.bosses.size,6);assert.ok(g.skills.slash>=2);assert.ok(g.elapsed<C.timeLimit);});
