import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game.js';
import {CONFIG as C,stageWaves} from '../src/config.js';
const fresh=id=>{const g=new Game(()=>.99);g.state='playing';g.phase='test';g.ultimateChoice=id;return g;};
test('blackhole and cannon charge 30 percent faster than exit without bypassing recharge lock',()=>{const gain=id=>{const g=fresh(id);g.killEnemy(g.createEnemy('slime',{x:200,y:300}));return g.ultimate;};for(const id of ['blackhole','cannon']){assert.ok(Math.abs(gain(id)/gain('exit')-1.3)<1e-9);const g=fresh(id);g.ultimate=100;g.useUltimate();g.killEnemy(g.createEnemy('slime',{x:200,y:300}));assert.equal(g.ultimate,0);}});
test('clones remain active beyond eight seconds and expire at nine seconds',()=>{const g=fresh('clones');g.ultimate=100;g.useUltimate();for(let i=0;i<85;i++)g.update(.1);assert.ok(g.ultimateEffectLeft>0);assert.equal(g.clonePositions().length,2);for(let i=0;i<6;i++)g.update(.1);assert.equal(g.ultimateEffectLeft,0);assert.equal(g.clonePositions().length,0);});
test('smog slows movement to 40 percent then releases; ghost slow remains separate',()=>{const g=fresh('exit');g.hero.x=200;g.hero.y=300;g.nav.move=(p,x,y)=>{p.x+=x;p.y+=y;};g.enemyAreas=[{kind:'smogPool',pos:{x:200,y:300},radius:48,fired:true,effect:3.5}];g.updateEnemyAreas(.01);g.update(.1,{x:1,y:0});assert.ok(Math.abs(g.hero.x-206.8)<.001);g.enemyAreas=[];for(let i=0;i<5;i++)g.update(.1);const before=g.hero.x;g.update(.1,{x:1,y:0});assert.ok(Math.abs(g.hero.x-before-17)<.001);g.reset();assert.equal(g.hero.smogSlowLeft,0);assert.equal(C.hero.slowMultiplier,.68);});
test('underrepresented enemies increase while basic horde and simultaneous cap stay unchanged',()=>{const counts={};for(let stage=1;stage<=6;stage++)for(const row of stageWaves(stage).flat())counts[row.type]=(counts[row.type]||0)+row.count;for(const [id,old] of Object.entries({chair:16,returnBird:16,cc:14,smog:14,hyena:14,chameleon:9}))assert.ok(counts[id]>old);assert.equal(counts.slime,413);assert.equal(C.limits.enemies,64);});
