import {CONFIG as C} from '../config.js';
import {AudioCues} from '../audio.js';
import {createInput} from '../input.js';
import {CoopGame,COOP_SKILLS,COOP_ULTIMATES} from './game.js';
import {CoopLink,loadPeer,createInvite,readInvite,interpolateSnapshots} from './network.js';
import {renderCoop} from './render.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),audio=new AudioCues();audio.muted=true;
let link=null,game=null,snapshot=null,localId=0,invite=null,remoteUltimate=null,localReady=false,running=false,loading=false,last=performance.now(),sendAt=0,inputAt=0,pendingUltimate=false,menuKey='',generation=0,previousSnapshot=null,snapshotAt=0;
const descriptions={exit:'画面全体を一掃して敵弾も消す。',clones:'9秒間、2人の分身で追撃。',rush:'6秒間、全周斬撃と受けるダメージ半減。',blackhole:'近くの敵を集める渦。相手の攻撃と合わせよう。',cannon:'太いビームで遠くの敵を貫く。'};
for(const id of COOP_ULTIMATES){const option=document.createElement('option');option.value=id;option.textContent=C.ultimate[id].name;$('ultimate-select').append(option);}
function showUltimateHelp(){$('ultimate-help').textContent=descriptions[$('ultimate-select').value];}showUltimateHelp();$('ultimate-select').onchange=showUltimateHelp;
try{invite=readInvite(location.hash);if(invite){$('create').hidden=true;$('join').hidden=false;$('network-status').textContent='友達からの招待です。必殺技を選んで参加しよう。';}}catch(error){$('network-status').textContent=error.message;}
const input=createInput(()=>running&&snapshot?.state==='playing'&&!snapshot.players[localId].down,code=>{if(snapshot?.state==='upgrade'){const match=/^(?:Digit|Numpad)([1-3])$/.exec(code);if(match){choose(Object.keys(COOP_SKILLS)[Number(match[1])-1]);return true;}}return false;});
function networkStatus(text){$('network-status').textContent=text;}
function resetToLobby(){generation++;loading=false;link?.close();link=null;game=null;snapshot=null;previousSnapshot=null;running=false;pendingUltimate=false;localReady=false;remoteUltimate=null;menuKey='';input.clear();$('play').hidden=true;$('lobby').hidden=false;$('create').hidden=false;$('create').disabled=false;$('join').hidden=true;$('join').disabled=false;$('ultimate-select').disabled=false;for(const id of ['ready','start','cancel','invite-panel'])$(id).hidden=true;invite=null;history.replaceState(null,'',location.pathname);audio.setScene('pause');}
function disconnected(message){if(snapshot&&['success','failure'].includes(snapshot.state)){running=false;game=null;$('connection-label').textContent='接続終了';return;}running=false;game=null;input.clear();audio.setScene('pause');if(!$('play').hidden){showModal('通信が切れました',message,[]);$('return').hidden=false;}else{networkStatus(message);$('cancel').hidden=false;$('cancel').textContent='部屋選択に戻る';}}
async function connect(joining){if(loading||link&&!link.closed)return;loading=true;const token=++generation;$('create').disabled=true;$('join').disabled=true;$('cancel').hidden=false;networkStatus('通信の準備中…');
 try{const Peer=await loadPeer();if(token!==generation)return;localId=joining?1:0;link=new CoopLink(Peer,{onStatus:status=>{if(status==='waiting'){const url=createInvite(location.href,link.room,link.key);$('invite-url').value=url;$('invite-panel').hidden=false;$('share').hidden=!navigator.share;networkStatus('招待URLを送って、友達を待とう。');}if(status==='connected'){$('ready').hidden=false;networkStatus('2人がつながりました！ 必殺技を決めて準備OKを押してください。');if(localId===0){$('start').hidden=false;link.send('welcome');}}},onMessage:onMessage,onClosed:disconnected});link.open(joining?invite:null);}catch(error){if(token===generation)disconnected(error.message);}finally{if(token===generation)loading=false;}}
function onMessage(m){if(m.type==='ready'){remoteUltimate=m.ultimate;updateReady();}else if(m.type==='start'){begin(false,m.ultimates);}else if(m.type==='snapshot'){previousSnapshot=snapshot;snapshot=m.data;snapshotAt=performance.now();paintHUD();}else if(m.type==='input'&&game)game.setInput(1,m.input);else if(m.type==='choice'&&game){game.choose(1,m.skill);snapshot=game.snapshot();link.sendSnapshot(snapshot);paintHUD();}}
function updateReady(){if(localId===0){$('start').disabled=!(localReady&&remoteUltimate);networkStatus(localReady&&remoteUltimate?'2人とも準備OK！ 出発できます。':localReady?'あなたは準備OK。相手の準備を待っています。':'相手が準備OK。あなたの必殺技を決めよう。');}else networkStatus('準備OK！ ホストが出発するのを待っています。');}
$('ready').onclick=()=>{if(!link?.connected)return;localReady=true;$('ultimate-select').disabled=true;$('ready').hidden=true;if(localId===1)link.send('ready',{ultimate:$('ultimate-select').value});updateReady();};
$('start').onclick=()=>{if(!link?.connected||!localReady||!remoteUltimate)return;const ultimates=[$('ultimate-select').value,remoteUltimate];if(link.send('start',{ultimates})){link.started=true;begin(true,ultimates);}};
function begin(host,ultimates){game=host?new CoopGame(ultimates):null;snapshot=host?game.snapshot():null;running=true;menuKey='';last=performance.now();sendAt=0;inputAt=0;pendingUltimate=false;input.clear();$('lobby').hidden=true;$('play').hidden=false;$('modal').hidden=true;canvas.focus({preventScroll:true});if(host)link.sendSnapshot(snapshot);paintHUD();}
function choose(skill){if(!running||snapshot?.state!=='upgrade'||snapshot.choice[localId])return;if(localId===0){game.choose(0,skill);snapshot=game.snapshot();link.sendSnapshot(snapshot);paintHUD();}else{link.send('choice',{skill});$('modal-text').textContent='選択を送信しました。相手の準備を待っています。';for(const b of $('choices').children)b.disabled=true;}}
function showModal(heading,message,choices){$('modal').hidden=false;$('modal-heading').textContent=heading;$('modal-text').textContent=message;$('choices').replaceChildren();$('return').hidden=true;for(const [id,label] of choices){const b=document.createElement('button');b.textContent=label;b.onclick=()=>choose(id);$('choices').append(b);}}
function paintHUD(){if(!snapshot)return;for(const p of snapshot.players){const panel=$(`player${p.id}`);if(!panel.children.length){panel.innerHTML='<b></b><span></span><div class="meter"><i></i></div><small></small><div class="meter charge"><i></i></div>';}
 panel.children[0].textContent=`${p.id+1}P${p.id===localId?' あなた':' 仲間'}`;panel.children[1].textContent=p.down?'救助待ち':`気力 ${Math.ceil(p.hp)}`;panel.children[2].firstChild.style.width=`${p.hp}%`;panel.children[3].textContent=`${C.ultimate[p.ultimate].name} ${Math.floor(p.gauge)}%`;panel.children[4].firstChild.style.width=`${p.gauge}%`;}
 const own=snapshot.players[localId],n=Math.ceil(snapshot.remaining);$('timer').textContent=`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;$('stage-label').textContent=snapshot.phase==='boss'?'魔王リーダー戦':snapshot.phase==='escape'?'2人で退勤ゲートへ':`WAVE ${snapshot.wave} / 2`;$('connection-label').textContent=`${localId===0?'ホスト':'参加者'}・接続中`;$('ultimate').classList.toggle('ready',own.gauge>=100&&!own.down&&!own.lock);$('ult-label').textContent=own.down?'救助待ち':own.effect>0?`${own.effect.toFixed(1)}秒`:own.lock>0?'準備中':own.gauge>=100?'発動！':`${Math.floor(own.gauge)}%`;
 $('battle-help').textContent=own.down?'仲間に近くへ来てもらおう。3秒で復活！':snapshot.players[1-localId].down?'仲間のそばに3秒いると救助できます！':'画面をなぞって移動・攻撃は自動';
 const key=`${snapshot.state}:${snapshot.choice.join(',')}`;if(key!==menuKey){menuKey=key;input.clear();if(snapshot.state==='upgrade'){const chosen=snapshot.choice[localId];showModal('あなたの技を強化',chosen?'選択済み。仲間の選択を待っています。':'それぞれ好きな技を選ぼう。2人とも選ぶと再開。',chosen?[]:Object.entries(COOP_SKILLS).map(([id,name],i)=>[id,`${i+1}. ${name} Lv.${own.skills[id]+1}`]));}else if(['success','failure'].includes(snapshot.state)){showModal(snapshot.state==='success'?'2人で定時退勤！':'今回は退勤できなかった…',`${snapshot.reason} / 撃破 ${snapshot.kills}体`,[]);$('return').hidden=false;running=false;game=null;}else $('modal').hidden=true;}
 audio.setScene(snapshot.state==='success'?'ending':snapshot.state!=='playing'?'pause':snapshot.phase==='boss'?'boss':'battle');}
$('create').onclick=()=>connect(false);$('join').onclick=()=>connect(true);$('cancel').onclick=()=>{resetToLobby();networkStatus('部屋を作って友達を招待しよう。');};$('return').onclick=$('cancel').onclick;$('leave').onclick=()=>{resetToLobby();networkStatus('協力プレイを終了しました。');};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('invite-url').value);networkStatus('招待URLをコピーしました。友達に送ってください。');}catch{$('invite-url').focus();$('invite-url').select();networkStatus('招待URLを選択しました。コピーして送ってください。');}};
$('share').onclick=async()=>{try{await navigator.share({title:'一緒に定時退勤しよう！',url:$('invite-url').value});}catch{}};
$('sound').onclick=async()=>{audio.setMuted(!audio.muted);if(!audio.muted)await audio.unlock();$('sound').textContent=audio.muted?'音 OFF':'音 ON';$('sound').setAttribute('aria-pressed',String(!audio.muted));};
window.addEventListener('blur',()=>{pendingUltimate=false;game?.setInput(0,{});if(link?.role==='guest')link.sendInput({});});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)link?.fail('画面が閉じられたため協力プレイを終了しました。2人とも画面を開いたままで遊んでください。');});
window.addEventListener('pagehide',()=>link?.close());setInterval(()=>link?.poll(),500);
function frame(now){const delta=Math.min((now-last)/1000,.1);last=now;if(running&&link?.connected){const controls=input.read();pendingUltimate||=controls.ultimate;if(localId===0&&game){game.setInput(0,{...controls,ultimate:pendingUltimate});pendingUltimate=false;game.update(delta);snapshot=game.snapshot();if(now-sendAt>=66||snapshot.state!=='playing'){sendAt=now;link.sendSnapshot(snapshot);}paintHUD();}else if(now-inputAt>=33){inputAt=now;link.sendInput({...controls,ultimate:pendingUltimate});pendingUltimate=false;}}
 renderCoop(ctx,localId===1&&snapshot?interpolateSnapshots(previousSnapshot,snapshot,(now-snapshotAt)/66):snapshot,localId,now/1000);requestAnimationFrame(frame);}
requestAnimationFrame(frame);
